### ISSUE TITLE
IndexError: boolean index did not match indexed array along dimension 0; dimension is 3834 but corresponding boolean dimension is 3415

### ISSUE THREAD

**Issue by Swayamtrupta** [rudolffu/qsofitmore#2]
Hi there!
Thank you so much for making this wrapper for PyQSOFit. It's really helpful! I am trying to analyze some SDSS spectra for which I prepared a master file with the qsofitmore code. It mostly works well but in some cases, it gives me the following error:

`Traceback (most recent call last):
  File "pyqsofit_more_fitting.py", line 114, in <module>
    q.Fit(name = None, deredden = True, wave_range = None, wave_mask =None, 
  File "/home/user/PyQSOFit_more/qsofitmore/qsofitmore/fitmodule.py", line 654, in Fit
    return super().Fit(name=name, nsmooth=nsmooth, and_or_mask=and_or_mask, reject_badpix=reject_badpix, 
  File "/home/user/Dropbox/PyQSOFit_more/PyQSOFit/PyQSOFit.py", line 480, in Fit
    self._DoLineFit(self.wave, self.line_flux, self.err, self.conti_fit)
  File "/home/user/PyQSOFit_more/qsofitmore/qsofitmore/fitmodule.py", line 930, in _DoLineFit
    med_sn = np.nanmedian(self.flux_prereduced[ind_n]/self.err_prereduced[ind_n])
IndexError: boolean index did not match indexed array along dimension 0; dimension is 3834 but corresponding boolean dimension is 3415`

I checked the .fits file and the length (in this case) of each column is 3836 each. To make a check, I tried to run the code with a text file (generated from the .fits) as input. But I still got the same error. _The spectrum works well with the standalone PyQSOFit code_. 
Any help will be deeply appreciated!

P.S. I am unable to add the .fits file. So, enclosing the .txt file here.

[spec-0411-51817-0092.txt](https://github.com/rudolffu/qsofitmore/files/8945075/spec-0411-51817-0092.txt)

**Comment by rudolffu** [comment]
Hi, I have checked your spectrum, which works fine in the latest version of this package.
The error was due to a non-standard way of boolean indexing in the previous versions, which has been fixed. Please use the latest version by cloning the GitHub repository to your local environment:
```
git clone https://github.com/rudolffu/qsofitmore.git
```
An example of the fitting result of your spectrum (parameters not tuned): 
![image](https://user-images.githubusercontent.com/23732534/174705843-e645c9e0-a94d-42b0-b824-8827b6b94104.png)

**Comment by Swayamtrupta** [comment]
Thanks! It works now for me as well.
