### ISSUE TITLE
Uncertain parameters for obtaining fit?

### ISSUE THREAD

**Issue by lesscrazyspacedust** [rudolffu/qsofitmore#7]
Hello!

I am new to pyQSOfit and trying to achieve a fit to certain parameters to get a good fwhm for MgII - the only issue is, I'm not sure what the parameters are supposed to be. My fit appears to be giving me a fit to the broad line and the narrow lines, but the fit I'm trying to achieve has only the broad lines. I've included my current parameters and fit, as well as the fit I'm trying to achieve--I pulled the spectrum from SDSS, and confirmed the RA/DEC/z for the spectrum. My fit gives me a broad fwhm of 1587.2345272478178, while it should be within 4168 +/- 1215 km/s. How would I achieve this? Thanks!

My parameters:
q = QSOFitNew(lam=wave, flux=flux, err=0.1 * np.ones_like(flux), z=z, path=path)
        
q.Fit(deredden=True, wave_range=None, decomposition_host=False, npca_gal=5, npca_qso=20, Fe_uv_op=True, poly=True, 
        MC=True, n_trails=20, linefit=True, tie_lambda=True, tie_width=True, tie_flux_1=True, tie_flux_2=True, save_result=True,
        plot_fig=True, save_fig=True)

My fit:
![download](https://github.com/rudolffu/qsofitmore/assets/144473248/188502ee-d24f-42ce-81e1-3904177dd7f0)

Goal fit:
![image](https://github.com/rudolffu/qsofitmore/assets/144473248/99ca1c74-9658-4718-8de6-f48b6a4b5cf1)

**Comment by rudolffu** [comment]
Hi, I would first try setting the `wave_range = [1500, 3800]` to remove the edges of the spectrum with higher noises, and `MC = False` to enable quick tests. You will notice some differences after setting the wavelength range. Turn on/off `poly` parameter to see if there are significant changes. These tests will help you find a good fit for the continuum.

You can then look at the individual emission lines. The CIII] line fitting in the "goal" fit figure shows a rather broad component which may not be True. Similarly, the broad component of your fit for MgII is too broad. If you have a better continuum fit, the baseline of the MgII might be lower, and the line width could be better constrained. 

If you have tried different settings and still get unreasonably wide/narrow profiles for certain lines/components, you may need to alter the line list parameter file (`qsopar.fits`). Those fitting constraints (e.g. `minsig`, `maxsig`, `voff`) are in log space, and they can be adjusted to better fit your data.
